title: BioLink Model
email: deepak.unni3@gmail.com
description: A high level datamodel for representing biological entities and their associations.

logo: "/assets/images/biolink-logo.png"

remote_theme: deepakunni3/just-the-docs

aux_links:
  "BioLink Model on GitHub":
    - "//github.com/biolink/biolink-model"

search_enabled: true
heading_anchors: true

# footer_content: "BioLink Model"

includes:
- docs
- about
- index.md
